
ALTER TABLE Account NOCHECK CONSTRAINT ALL						ALTER TABLE Account DISABLE TRIGGER ALL
ALTER TABLE AccountAuthorization NOCHECK CONSTRAINT ALL			ALTER TABLE AccountAuthorization DISABLE TRIGGER ALL
ALTER TABLE AccountAuthorizationGoals NOCHECK CONSTRAINT ALL	ALTER TABLE AccountAuthorizationGoals DISABLE TRIGGER ALL
ALTER TABLE AccountBank NOCHECK CONSTRAINT ALL					ALTER TABLE AccountBank DISABLE TRIGGER ALL
ALTER TABLE AccountBill NOCHECK CONSTRAINT ALL					ALTER TABLE AccountBill DISABLE TRIGGER ALL
ALTER TABLE AccountBillAmount NOCHECK CONSTRAINT ALL			ALTER TABLE AccountBillAmount DISABLE TRIGGER ALL
ALTER TABLE AccountBillAmountHistory NOCHECK CONSTRAINT ALL		ALTER TABLE AccountBillAmountHistory DISABLE TRIGGER ALL
ALTER TABLE AccountBillHistory NOCHECK CONSTRAINT ALL			ALTER TABLE AccountBillHistory DISABLE TRIGGER ALL
ALTER TABLE AccountChild NOCHECK CONSTRAINT ALL					ALTER TABLE AccountChild DISABLE TRIGGER ALL
ALTER TABLE AccountInvoice NOCHECK CONSTRAINT ALL				ALTER TABLE AccountInvoice DISABLE TRIGGER ALL
ALTER TABLE AccountInvoiceItem NOCHECK CONSTRAINT ALL			ALTER TABLE AccountInvoiceItem DISABLE TRIGGER ALL
ALTER TABLE AccountRecurring NOCHECK CONSTRAINT ALL				ALTER TABLE AccountRecurring DISABLE TRIGGER ALL
ALTER TABLE AccountRecurringAmount NOCHECK CONSTRAINT ALL		ALTER TABLE AccountRecurringAmount DISABLE TRIGGER ALL
ALTER TABLE AccountRecurringBatch NOCHECK CONSTRAINT ALL		ALTER TABLE AccountRecurringBatch DISABLE TRIGGER ALL
ALTER TABLE AccountTransaction NOCHECK CONSTRAINT ALL			ALTER TABLE AccountTransaction DISABLE TRIGGER ALL
ALTER TABLE AccountTransactionBatch NOCHECK CONSTRAINT ALL		ALTER TABLE AccountTransactionBatch DISABLE TRIGGER ALL
ALTER TABLE AccountTransactionBill NOCHECK CONSTRAINT ALL		ALTER TABLE AccountTransactionBill DISABLE TRIGGER ALL
ALTER TABLE AccountVoucher NOCHECK CONSTRAINT ALL				ALTER TABLE AccountVoucher DISABLE TRIGGER ALL
ALTER TABLE AccountVoucherItem NOCHECK CONSTRAINT ALL			ALTER TABLE AccountVoucherItem DISABLE TRIGGER ALL
ALTER TABLE Application NOCHECK CONSTRAINT ALL					ALTER TABLE Application DISABLE TRIGGER ALL
ALTER TABLE ApplicationWIA NOCHECK CONSTRAINT ALL				ALTER TABLE ApplicationWIA DISABLE TRIGGER ALL
ALTER TABLE ApplicationPPO NOCHECK CONSTRAINT ALL				ALTER TABLE ApplicationPPO DISABLE TRIGGER ALL
ALTER TABLE ApplicationVeteran NOCHECK CONSTRAINT ALL			ALTER TABLE ApplicationVeteran DISABLE TRIGGER ALL
ALTER TABLE Appeal NOCHECK CONSTRAINT ALL						ALTER TABLE Appeal DISABLE TRIGGER ALL
ALTER TABLE Assessment NOCHECK CONSTRAINT ALL					ALTER TABLE Assessment DISABLE TRIGGER ALL
ALTER TABLE AssessmentAddictionHealth NOCHECK CONSTRAINT ALL	ALTER TABLE AssessmentAddictionHealth DISABLE TRIGGER ALL
ALTER TABLE AssessmentEval NOCHECK CONSTRAINT ALL				ALTER TABLE AssessmentEval DISABLE TRIGGER ALL
ALTER TABLE AssessmentWorkHist NOCHECK CONSTRAINT ALL			ALTER TABLE AssessmentWorkHist DISABLE TRIGGER ALL
ALTER TABLE AssessSelfMatrix NOCHECK CONSTRAINT ALL				ALTER TABLE AssessSelfMatrix DISABLE TRIGGER ALL
ALTER TABLE AssetAssessment NOCHECK CONSTRAINT ALL				ALTER TABLE AssetAssessment DISABLE TRIGGER ALL
ALTER TABLE AssetsSavingsAccount NOCHECK CONSTRAINT ALL			ALTER TABLE AssetsSavingsAccount DISABLE TRIGGER ALL
ALTER TABLE BarList NOCHECK CONSTRAINT ALL						ALTER TABLE BarList DISABLE TRIGGER ALL
ALTER TABLE BarListReason NOCHECK CONSTRAINT ALL				ALTER TABLE BarListReason DISABLE TRIGGER ALL
ALTER TABLE BatchTransaction NOCHECK CONSTRAINT ALL				ALTER TABLE BatchTransaction DISABLE TRIGGER ALL
ALTER TABLE Call NOCHECK CONSTRAINT ALL							ALTER TABLE Call DISABLE TRIGGER ALL
ALTER TABLE CallReason NOCHECK CONSTRAINT ALL					ALTER TABLE CallReason DISABLE TRIGGER ALL
ALTER TABLE ChronicHomeless NOCHECK CONSTRAINT ALL				ALTER TABLE ChronicHomeless DISABLE TRIGGER ALL
ALTER TABLE ClientFiles NOCHECK CONSTRAINT ALL					ALTER TABLE ClientFiles DISABLE TRIGGER ALL
ALTER TABLE ClientIdentifier NOCHECK CONSTRAINT ALL				ALTER TABLE ClientIdentifier DISABLE TRIGGER ALL
ALTER TABLE ClientPhone NOCHECK CONSTRAINT ALL					ALTER TABLE ClientPhone DISABLE TRIGGER ALL
ALTER TABLE ClientRace NOCHECK CONSTRAINT ALL					ALTER TABLE ClientRace DISABLE TRIGGER ALL
ALTER TABLE ClientScreening NOCHECK CONSTRAINT ALL				ALTER TABLE ClientScreening DISABLE TRIGGER ALL
ALTER TABLE ClientSignature NOCHECK CONSTRAINT ALL				ALTER TABLE ClientSignature DISABLE TRIGGER ALL
ALTER TABLE cmAddictionHealth NOCHECK CONSTRAINT ALL			ALTER TABLE cmAddictionHealth DISABLE TRIGGER ALL
ALTER TABLE cmAddress NOCHECK CONSTRAINT ALL					ALTER TABLE cmAddress DISABLE TRIGGER ALL
ALTER TABLE cmAlias NOCHECK CONSTRAINT ALL						ALTER TABLE cmAlias DISABLE TRIGGER ALL
ALTER TABLE cmCaseAssign NOCHECK CONSTRAINT ALL					ALTER TABLE cmCaseAssign DISABLE TRIGGER ALL
ALTER TABLE cmClient NOCHECK CONSTRAINT ALL						ALTER TABLE cmClient DISABLE TRIGGER ALL
ALTER TABLE cmClient_Address NOCHECK CONSTRAINT ALL				ALTER TABLE cmClient_Address DISABLE TRIGGER ALL
ALTER TABLE cmClntEval NOCHECK CONSTRAINT ALL					ALTER TABLE cmClntEval DISABLE TRIGGER ALL
ALTER TABLE cmDocumentCheckList NOCHECK CONSTRAINT ALL			ALTER TABLE cmDocumentCheckList DISABLE TRIGGER ALL
ALTER TABLE cmFamilyAccFile NOCHECK CONSTRAINT ALL				ALTER TABLE cmFamilyAccFile DISABLE TRIGGER ALL
ALTER TABLE cmFamilyMemFile NOCHECK CONSTRAINT ALL				ALTER TABLE cmFamilyMemFile DISABLE TRIGGER ALL
ALTER TABLE cmFinancialAssess NOCHECK CONSTRAINT ALL			ALTER TABLE cmFinancialAssess DISABLE TRIGGER ALL
ALTER TABLE cmGoals NOCHECK CONSTRAINT ALL						ALTER TABLE cmGoals DISABLE TRIGGER ALL
ALTER TABLE cmInfoRelease NOCHECK CONSTRAINT ALL				ALTER TABLE cmInfoRelease DISABLE TRIGGER ALL
ALTER TABLE cmInterOther NOCHECK CONSTRAINT ALL					ALTER TABLE cmInterOther DISABLE TRIGGER ALL
ALTER TABLE cmWorkHistoryHeadStart NOCHECK CONSTRAINT ALL		ALTER TABLE cmWorkHistoryHeadStart DISABLE TRIGGER ALL
ALTER TABLE cmWorkHistHSHistory NOCHECK CONSTRAINT ALL			ALTER TABLE cmWorkHistHSHistory DISABLE TRIGGER ALL
ALTER TABLE cmTestRslts NOCHECK CONSTRAINT ALL					ALTER TABLE cmTestRslts DISABLE TRIGGER ALL
ALTER TABLE cmWorkHist NOCHECK CONSTRAINT ALL					ALTER TABLE cmWorkHist DISABLE TRIGGER ALL
ALTER TABLE cmWorkHistHistory NOCHECK CONSTRAINT ALL			ALTER TABLE cmWorkHistHistory DISABLE TRIGGER ALL
--ALTER TABLE cmWorkHistHeadstart NOCHECK CONSTRAINT ALL			ALTER TABLE cmWorkHistHeadStart NOCHECK CONSTRAINT ALL
ALTER TABLE WorkHistoryBenefits NOCHECK CONSTRAINT ALL			ALTER TABLE WorkHistoryBenefits DISABLE TRIGGER ALL;
ALTER TABLE Legal NOCHECK CONSTRAINT ALL						ALTER TABLE Legal DISABLE TRIGGER ALL
ALTER TABLE Spirituality NOCHECK CONSTRAINT ALL					ALTER TABLE Spirituality DISABLE TRIGGER ALL
ALTER TABLE Transportation NOCHECK CONSTRAINT ALL				ALTER TABLE Transportation DISABLE TRIGGER ALL
ALTER TABLE CourtCase NOCHECK CONSTRAINT ALL					ALTER TABLE CourtCase DISABLE TRIGGER ALL
ALTER TABLE CourtCaseOutcome NOCHECK CONSTRAINT ALL				ALTER TABLE CourtCaseOutcome DISABLE TRIGGER ALL
--ALTER TABLE Defect NOCHECK CONSTRAINT ALL						ALTER TABLE Defect DISABLE TRIGGER ALL
ALTER TABLE DocumentCatalog NOCHECK CONSTRAINT ALL				ALTER TABLE DocumentCatalog DISABLE TRIGGER ALL
ALTER TABLE Diagnosis NOCHECK CONSTRAINT ALL					ALTER TABLE Diagnosis DISABLE TRIGGER ALL
ALTER TABLE DietaryAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE DietaryAssessment DISABLE TRIGGER ALL
ALTER TABLE DietaryTypes NOCHECK CONSTRAINT ALL					ALTER TABLE DietaryTypes DISABLE TRIGGER ALL
ALTER TABLE Disabilities NOCHECK CONSTRAINT ALL					ALTER TABLE Disabilities DISABLE TRIGGER ALL
ALTER TABLE DocumentLink NOCHECK CONSTRAINT ALL					ALTER TABLE DocumentLink DISABLE TRIGGER ALL
ALTER TABLE DomesticViolenceAssessment NOCHECK CONSTRAINT ALL	ALTER TABLE DomesticViolenceAssessment DISABLE TRIGGER ALL
ALTER TABLE DVCrimes NOCHECK CONSTRAINT ALL						ALTER TABLE DVCrimes DISABLE TRIGGER ALL
ALTER TABLE DynamicFormPaused NOCHECK CONSTRAINT ALL			ALTER TABLE DynamicFormPaused DISABLE TRIGGER ALL
ALTER TABLE EducationAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE EducationAssessment DISABLE TRIGGER ALL
ALTER TABLE EducationSpecialNeeds NOCHECK CONSTRAINT ALL		ALTER TABLE EducationSpecialNeeds DISABLE TRIGGER ALL
ALTER TABLE EducationHeadStart NOCHECK CONSTRAINT ALL			ALTER TABLE EducationHeadStart DISABLE TRIGGER ALL
ALTER TABLE EducationSubjects NOCHECK CONSTRAINT ALL			ALTER TABLE EducationSubjects DISABLE TRIGGER ALL
ALTER TABLE EmploymentAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE EmploymentAssessment DISABLE TRIGGER ALL
ALTER TABLE EmploymentAssessment_VA NOCHECK CONSTRAINT ALL		ALTER TABLE EmploymentAssessment_VA DISABLE TRIGGER ALL
ALTER TABLE EncounterActivity NOCHECK CONSTRAINT ALL			ALTER TABLE EncounterActivity DISABLE TRIGGER ALL
ALTER TABLE Encounter NOCHECK CONSTRAINT ALL					ALTER TABLE Encounter DISABLE TRIGGER ALL
ALTER TABLE EncounterEHR NOCHECK CONSTRAINT ALL					ALTER TABLE EncounterEHR DISABLE TRIGGER ALL
ALTER TABLE Enrollment NOCHECK CONSTRAINT ALL					ALTER TABLE Enrollment DISABLE TRIGGER ALL
ALTER TABLE EnrollmentAccount NOCHECK CONSTRAINT ALL			ALTER TABLE EnrollmentAccount DISABLE TRIGGER ALL
ALTER TABLE EnrollmentCase NOCHECK CONSTRAINT ALL				ALTER TABLE EnrollmentCase DISABLE TRIGGER ALL
ALTER TABLE EnrollmentEducation NOCHECK CONSTRAINT ALL			ALTER TABLE EnrollmentEducation DISABLE TRIGGER ALL
ALTER TABLE EnrollmentParticipation NOCHECK CONSTRAINT ALL		ALTER TABLE EnrollmentParticipation DISABLE TRIGGER ALL
ALTER TABLE EnrollmentPosted NOCHECK CONSTRAINT ALL				ALTER TABLE EnrollmentPosted DISABLE TRIGGER ALL
ALTER TABLE EnrollmentSchool NOCHECK CONSTRAINT ALL				ALTER TABLE EnrollmentSchool DISABLE TRIGGER ALL
ALTER TABLE EnrollmentWIA NOCHECK CONSTRAINT ALL				ALTER TABLE EnrollmentWIA DISABLE TRIGGER ALL
ALTER TABLE EnrollmentHistory NOCHECK CONSTRAINT ALL			ALTER TABLE EnrollmentHistory DISABLE TRIGGER ALL
ALTER TABLE EnrollmentIndivdualPlan NOCHECK CONSTRAINT ALL		ALTER TABLE EnrollmentIndivdualPlan DISABLE TRIGGER ALL
ALTER TABLE EntityBasicClient NOCHECK CONSTRAINT ALL			ALTER TABLE EntityBasicClient DISABLE TRIGGER ALL
ALTER TABLE EntityChild NOCHECK CONSTRAINT ALL					ALTER TABLE EntityChild	DISABLE TRIGGER ALL
ALTER TABLE EntityFlat NOCHECK CONSTRAINT ALL					ALTER TABLE EntityFlat DISABLE TRIGGER ALL
ALTER TABLE EntityList NOCHECK CONSTRAINT ALL					ALTER TABLE EntityList DISABLE TRIGGER ALL
ALTER TABLE EntityTimeCode NOCHECK CONSTRAINT ALL				ALTER TABLE EntityTimeCode DISABLE TRIGGER ALL
ALTER TABLE FamilyAlias NOCHECK CONSTRAINT ALL					ALTER TABLE FamilyAlias DISABLE TRIGGER ALL
ALTER TABLE FileUpload NOCHECK CONSTRAINT ALL					ALTER TABLE FileUpload DISABLE TRIGGER ALL
ALTER TABLE FinancialAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE FinancialAssessment DISABLE TRIGGER ALL
ALTER TABLE FinancialDeduction NOCHECK CONSTRAINT ALL			ALTER TABLE FinancialDeduction DISABLE TRIGGER ALL
ALTER TABLE FinancialEvaluation NOCHECK CONSTRAINT ALL			ALTER TABLE FinancialEvaluation DISABLE TRIGGER ALL
ALTER TABLE FinancialExpenseDetail NOCHECK CONSTRAINT ALL		ALTER TABLE FinancialExpenseDetail DISABLE TRIGGER ALL
ALTER TABLE FinancialExpense NOCHECK CONSTRAINT ALL				ALTER TABLE FinancialExpense DISABLE TRIGGER ALL
ALTER TABLE FinancialIncome NOCHECK CONSTRAINT ALL				ALTER TABLE FinancialIncome DISABLE TRIGGER ALL
ALTER TABLE FollowUp NOCHECK CONSTRAINT ALL						ALTER TABLE FollowUp DISABLE TRIGGER ALL
ALTER TABLE FosterCareAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE FosterCareAssessment DISABLE TRIGGER ALL
ALTER TABLE GoalProgress NOCHECK CONSTRAINT ALL					ALTER TABLE GoalProgress DISABLE TRIGGER ALL
ALTER TABLE HeadStartMedAssessment NOCHECK CONSTRAINT ALL		ALTER TABLE HeadStartMedAssessment DISABLE TRIGGER ALL
ALTER TABLE HazMatAssessment NOCHECK CONSTRAINT ALL				ALTER TABLE HazMatAssessment DISABLE TRIGGER ALL
ALTER TABLE Hearing NOCHECK CONSTRAINT ALL						ALTER TABLE Hearing DISABLE TRIGGER ALL
ALTER TABLE HearingCrime NOCHECK CONSTRAINT ALL					ALTER TABLE HearingCrime DISABLE TRIGGER ALL
ALTER TABLE HIVAssessment NOCHECK CONSTRAINT ALL				ALTER TABLE HIVAssessment DISABLE TRIGGER ALL
ALTER TABLE HmisDataAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE HmisDataAssessment DISABLE TRIGGER ALL
ALTER TABLE HazardousMaterial NOCHECK CONSTRAINT ALL			ALTER TABLE HazardousMaterial DISABLE TRIGGER ALL
ALTER TABLE ImmunizationRecord NOCHECK CONSTRAINT ALL			ALTER TABLE ImmunizationRecord DISABLE TRIGGER ALL

ALTER TABLE IncidentAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE IncidentAssessment DISABLE TRIGGER ALL
ALTER TABLE IncidentAssessmentType NOCHECK CONSTRAINT ALL		ALTER TABLE IncidentAssessmentType DISABLE TRIGGER ALL
ALTER TABLE Insurance NOCHECK CONSTRAINT ALL					ALTER TABLE Insurance DISABLE TRIGGER ALL
ALTER TABLE InsuranceAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE InsuranceAssessment DISABLE TRIGGER ALL
ALTER TABLE LeaseAgreement NOCHECK CONSTRAINT ALL				ALTER TABLE LeaseAgreement DISABLE TRIGGER ALL
ALTER TABLE LetterEntity NOCHECK CONSTRAINT ALL					ALTER TABLE LetterEntity DISABLE TRIGGER ALL
ALTER TABLE LIHEAPAssessment NOCHECK CONSTRAINT ALL				ALTER TABLE LIHEAPAssessment DISABLE TRIGGER ALL
ALTER TABLE MedicalAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE MedicalAssessment DISABLE TRIGGER ALL
ALTER TABLE MedicalAssessment_HealthDetails NOCHECK CONSTRAINT ALL		ALTER TABLE MedicalAssessment_HealthDetails  DISABLE TRIGGER ALL
--ALTER TABLE MedicationLink NOCHECK CONSTRAINT ALL				ALTER TABLE MedicationLink DISABLE TRIGGER ALL
--ALTER TABLE MedicationAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE MedicationAssessment DISABLE TRIGGER ALL
--ALTER TABLE Medication NOCHECK CONSTRAINT ALL					ALTER TABLE Medication DISABLE TRIGGER ALL
ALTER TABLE MilitaryServiceHistory NOCHECK CONSTRAINT ALL		ALTER TABLE MilitaryServiceHistory DISABLE TRIGGER ALL
ALTER TABLE NutritionPreference NOCHECK CONSTRAINT ALL			ALTER TABLE NutritionPreference DISABLE TRIGGER ALL
ALTER TABLE PregnancyAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE PregnancyAssessment DISABLE TRIGGER ALL
ALTER TABLE PrescriptClntRef NOCHECK CONSTRAINT ALL				ALTER TABLE PrescriptClntRef DISABLE TRIGGER ALL
ALTER TABLE AssessmentPrescription NOCHECK CONSTRAINT ALL		ALTER TABLE AssessmentPrescription DISABLE TRIGGER ALL
ALTER TABLE PrenatalCare NOCHECK CONSTRAINT ALL					ALTER TABLE PrenatalCare DISABLE TRIGGER ALL
ALTER TABLE ProviderClientMeeting NOCHECK CONSTRAINT ALL		ALTER TABLE ProviderClientMeeting DISABLE TRIGGER ALL
ALTER TABLE ProviderClientRelationship NOCHECK CONSTRAINT ALL	ALTER TABLE ProviderClientRelationship DISABLE TRIGGER ALL
ALTER TABLE ProficientLanguage NOCHECK CONSTRAINT ALL			ALTER TABLE ProficientLanguage DISABLE TRIGGER ALL
ALTER TABLE QuarterlyWage NOCHECK CONSTRAINT ALL				ALTER TABLE QuarterlyWage DISABLE TRIGGER ALL
ALTER TABLE RecentEntity NOCHECK CONSTRAINT ALL					ALTER TABLE RecentEntity DISABLE TRIGGER ALL
ALTER TABLE Service NOCHECK CONSTRAINT ALL						ALTER TABLE Service DISABLE TRIGGER ALL
ALTER TABLE ServiceActionPlan NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceActionPlan DISABLE TRIGGER ALL
ALTER TABLE ServiceAttendance NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceAttendance DISABLE TRIGGER ALL
ALTER TABLE ServiceCheckIn NOCHECK CONSTRAINT ALL				ALTER TABLE ServiceCheckIn DISABLE TRIGGER ALL
ALTER TABLE ServiceCheckInPosted NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceCheckInPosted DISABLE TRIGGER ALL
ALTER TABLE ServiceDirect NOCHECK CONSTRAINT ALL				ALTER TABLE ServiceDirect DISABLE TRIGGER ALL
ALTER TABLE ServiceFamilyInfo NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceFamilyInfo DISABLE TRIGGER ALL
ALTER TABLE ServiceIndirect NOCHECK CONSTRAINT ALL				ALTER TABLE ServiceIndirect DISABLE TRIGGER ALL
ALTER TABLE ServiceInspection NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceInspection DISABLE TRIGGER ALL
ALTER TABLE ServiceParticipation NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceParticipation DISABLE TRIGGER ALL
ALTER TABLE ServiceReferral NOCHECK CONSTRAINT ALL				ALTER TABLE ServiceReferral DISABLE TRIGGER ALL
ALTER TABLE ServiceReservation NOCHECK CONSTRAINT ALL			ALTER TABLE ServiceReservation DISABLE TRIGGER ALL
ALTER TABLE ServiceWIA NOCHECK CONSTRAINT ALL					ALTER TABLE ServiceWIA DISABLE TRIGGER ALL
ALTER TABLE StudentFood NOCHECK CONSTRAINT ALL					ALTER TABLE StudentFood DISABLE TRIGGER ALL
ALTER TABLE TimeEntry NOCHECK CONSTRAINT ALL					ALTER TABLE TimeEntry DISABLE TRIGGER ALL
ALTER TABLE Participant NOCHECK CONSTRAINT ALL					ALTER TABLE Participant DISABLE TRIGGER ALL
ALTER TABLE VeteranAssessment NOCHECK CONSTRAINT ALL			ALTER TABLE VeteranAssessment DISABLE TRIGGER ALL
ALTER TABLE VeteranAssessmentJournal NOCHECK CONSTRAINT ALL		ALTER TABLE VeteranAssessmentJournal DISABLE TRIGGER ALL
ALTER TABLE VulnerabilityIndex NOCHECK CONSTRAINT ALL			ALTER TABLE VulnerabilityIndex DISABLE TRIGGER ALL
ALTER TABLE VulnerabilityHealthInsurance NOCHECK CONSTRAINT ALL	ALTER TABLE VulnerabilityHealthInsurance DISABLE TRIGGER ALL
ALTER TABLE VulnerabilityMoneyType NOCHECK CONSTRAINT ALL		ALTER TABLE VulnerabilityMoneyType DISABLE TRIGGER ALL
ALTER TABLE VulnerabilityHousingBarriers NOCHECK CONSTRAINT ALL ALTER TABLE VulnerabilityHousingBarriers DISABLE TRIGGER ALL
ALTER TABLE VulnerabilityWarsServedIn NOCHECK CONSTRAINT ALL	ALTER TABLE VulnerabilityWarsServedIn DISABLE TRIGGER ALL
ALTER TABLE Visit NOCHECK CONSTRAINT ALL						ALTER TABLE Visit DISABLE TRIGGER ALL
ALTER TABLE WaitingList NOCHECK CONSTRAINT ALL					ALTER TABLE WaitingList DISABLE TRIGGER ALL
ALTER TABLE WaitingListHousing NOCHECK CONSTRAINT ALL			ALTER TABLE WaitingListHousing DISABLE TRIGGER ALL
ALTER TABLE WorkflowInstance NOCHECK CONSTRAINT ALL				ALTER TABLE WorkflowInstance DISABLE TRIGGER ALL
ALTER TABLE Wisconsin NOCHECK CONSTRAINT ALL					ALTER TABLE Wisconsin DISABLE TRIGGER ALL

DELETE FROM AccountInvoice WHERE InvoiceID IN (SELECT InvoiceID FROM AccountInvoiceItem 
	WHERE BillID IN (SELECT BillID FROM AccountBill WHERE (AccountID IN (SELECT AccountID FROM cmClient))
	OR (BillID IN (SELECT BillID FROM AccountBillAmount WHERE AccountID IN (SELECT AccountID FROM cmClient)))))
	DBCC CHECKIDENT( 'AccountInvoice', RESEED )
DELETE FROM AccountTransaction WHERE TransactionID IN (SELECT TransactionID FROM AccountTransactionBill 
	WHERE BillID IN (SELECT BillID FROM AccountBill WHERE (AccountID IN (SELECT AccountID FROM cmClient))
	OR (BillID IN (SELECT BillID FROM AccountBillAmount WHERE AccountID IN (SELECT AccountID FROM cmClient)))))
	DBCC CHECKIDENT( 'AccountTransaction', RESEED )
DELETE FROM AccountBill	WHERE (AccountID IN (SELECT AccountID FROM cmClient)) 
	OR (BillID IN (SELECT BillID FROM AccountBillAmount WHERE AccountID IN (SELECT AccountID FROM cmClient)))
	DBCC CHECKIDENT( 'AccountBill', RESEED )
DELETE FROM AccountChild WHERE (AccountID IN (SELECT AccountID FROM cmClient)) OR (ChildID IN (SELECT AccountID FROM cmClient))
	DBCC CHECKIDENT('AccountChild', RESEED ) 
DELETE FROM AccountTransactionBatch WHERE AccountID IN (SELECT AccountID FROM cmClient)
	DBCC CHECKIDENT('AccountTransactionBatch', RESEED ) 
DELETE FROM AccountPayment WHERE (SourceID IN (SELECT AccountID FROM cmClient)) 
	OR (DestinationID IN (SELECT AccountID FROM cmClient))
	DBCC CHECKIDENT('AccountPayment', RESEED ) 
DELETE FROM AccountRecurring WHERE AccountID IN (SELECT AccountID FROM cmClient)
	DBCC CHECKIDENT('AccountRecurring', RESEED ) 
DELETE FROM AccountRecurringAmount WHERE AccountID IN (SELECT AccountID FROM cmClient)
	DBCC CHECKIDENT('AccountRecurringAmount', RESEED ) 
DELETE FROM AccountRecurringBatch WHERE AccountID IN (SELECT AccountID FROM cmClient)
	DBCC CHECKIDENT('AccountRecurringBatch', RESEED ) 

DELETE FROM ClientBenefits	DBCC CHECKIDENT( 'ClientBenefits', RESEED, 1 )
DELETE FROM AccountFlat WHERE AccountID IN (SELECT AccountID FROM cmClient)
DELETE FROM ExpensesPaid  DBCC CHECKIDENT( 'ExpensesPaid', RESEED, 1 )
DELETE FROM DietaryAssessment  DBCC CHECKIDENT( 'DietaryAssessment', RESEED, 1 )
DELETE FROM DietaryTypes  
DELETE FROM ClientRace 
DELETE FROM Account WHERE AccountID IN (SELECT AccountID FROM cmClient)	DBCC CHECKIDENT( 'Account', RESEED )
DELETE FROM AccountBank WHERE BankID NOT IN (SELECT BankID FROM Account) DBCC CHECKIDENT('AccountBank', RESEED ) 
DELETE FROM AccountPaymentVoid WHERE (PaymentID NOT IN (SELECT PaymentID FROM AccountPayment)) 
	OR (TransactionID NOT IN (SELECT TransactionID FROM AccountTransaction))
DELETE FROM AccountAuthorization 		DBCC CHECKIDENT( 'AccountAuthorization', RESEED, 1 )
DELETE FROM AccountAuthorizationGoals   DBCC CHECKIDENT( 'AccountAuthorizationGoals', RESEED, 1 )
DELETE FROM Application					DBCC CHECKIDENT( 'Application', RESEED, 1 )
DELETE FROM ApplicationWIA				DBCC CHECKIDENT( 'ApplicationWIA', RESEED, 1 )
DELETE FROM ApplicationPPO				DBCC CHECKIDENT( 'ApplicationPPO', RESEED, 1 )
DELETE FROM ApplicationVeteran			
DELETE FROM Appeal						DBCC CHECKIDENT( 'Appeal', RESEED, 1)
DELETE FROM Assessment					DBCC CHECKIDENT( 'Assessment', RESEED, 1 )
DELETE FROM AssessmentEval				DBCC CHECKIDENT( 'AssessmentEval', RESEED, 1 )
DELETE FROM AssessmentWorkHist			DBCC CHECKIDENT( 'AssessmentWorkHist', RESEED, 1 )
DELETE FROM AssessSelfMatrix			DBCC CHECKIDENT( 'AssessSelfMatrix', RESEED, 1 )
DELETE FROM AssetAssessment				DBCC CHECKIDENT( 'AssetAssessment', RESEED, 1)
DELETE FROM AssetsSavingsAccount		DBCC CHECKIDENT( 'AssetsSavingsAccount', RESEED, 1)
DELETE FROM BarList						DBCC CHECKIDENT( 'BarList', RESEED, 1 )
DELETE FROM BarListReason
DELETE FROM BatchTransaction			DBCC CHECKIDENT( 'BatchTransaction', RESEED, 1 )
DELETE FROM Call						DBCC CHECKIDENT( 'Call', RESEED, 1 )
DELETE FROM CallReason					
DELETE FROM ChronicHomeless				DBCC CHECKIDENT( 'ChronicHomeless', RESEED, 1 )
DELETE FROM ClientFiles					DBCC CHECKIDENT( 'ClientFiles', RESEED, 1 )
DELETE FROM ClientIdentifier			DBCC CHECKIDENT( 'ClientIdentifier', RESEED, 1 )
DELETE FROM ClientPhone					DBCC CHECKIDENT( 'ClientPhone', RESEED, 1 )
DELETE FROM ClientRace					
DELETE FROM ClientSignature			
DELETE FROM ClientScreening				DBCC CHECKIDENT( 'ClientScreening', RESEED, 1 )	
DELETE FROM cmAddictionHealth			DBCC CHECKIDENT( 'cmAddictionHealth', RESEED, 1 )
DELETE FROM AssessmentAddictionHealth	DBCC CHECKIDENT( 'AssessmentAddictionHealth', RESEED, 1 ) 
DELETE FROM cmAddress					DBCC CHECKIDENT( 'cmAddress', RESEED, 1 )
DELETE FROM cmAlias						DBCC CHECKIDENT( 'cmAlias', RESEED, 1 )
DELETE FROM cmCaseAssign				DBCC CHECKIDENT( 'cmCaseAssign', RESEED, 1 )

DELETE FROM cmClient_Address			
DELETE FROM cmClient					DBCC CHECKIDENT( 'cmClient', RESEED, 1 )
DELETE FROM cmClntEval					DBCC CHECKIDENT( 'cmClntEval', RESEED, 1 )
DELETE FROM cmDocumentCheckList			DBCC CHECKIDENT( 'cmDocumentCheckList', RESEED, 1 )
DELETE FROM cmFamilyAccFile				DBCC CHECKIDENT( 'cmFamilyAccFile', RESEED, 1 )
DELETE FROM cmFamilyMemFile				DBCC CHECKIDENT( 'cmFamilyMemFile', RESEED, 1 )
DELETE FROM cmFinancialAssess			DBCC CHECKIDENT( 'cmFinancialAssess', RESEED, 1 )
DELETE FROM cmGoals						DBCC CHECKIDENT( 'cmGoals', RESEED, 1 )
DELETE FROM cmInfoRelease				DBCC CHECKIDENT( 'cmInfoRelease', RESEED, 1 )
DELETE FROM cmInterOther				DBCC CHECKIDENT( 'cmInterOther', RESEED, 1 )
DELETE FROM cmWorkHistoryHeadStart		--DBCC CHECKIDENT( 'cmWorkHistoryHeadStart', RESEED, 1 )
DELETE FROM cmWorkHistHSHistory			DBCC CHECKIDENT( 'cmWorkHistHSHistory', RESEED, 1 )
DELETE FROM cmTestRslts					DBCC CHECKIDENT( 'cmTestRslts', RESEED, 1 )
DELETE FROM cmWorkHist					DBCC CHECKIDENT( 'cmWorkHist', RESEED, 1 )
DELETE FROM cmWorkHistHistory			DBCC CHECKIDENT( 'cmWorkHistHistory', RESEED, 1 )
DELETE FROM WorkHistoryBenefits			DBCC CHECKIDENT( 'WorkHistoryBenefits', RESEED, 1)
DELETE FROM Legal						DBCC CHECKIDENT( 'Legal', RESEED, 1 )
DELETE FROM LIHEAPAssessment			DBCC CHECKIDENT( 'LIHEAPAssessment', RESEED, 1 )
DELETE FROM LetterEntity				DBCC CHECKIDENT( 'LetterEntity', RESEED, 1)
DELETE FROM Spirituality				DBCC CHECKIDENT( 'Spirituality', RESEED, 1 )
DELETE FROM Transportation				DBCC CHECKIDENT( 'Transportation', RESEED, 1 )
DELETE FROM CourtCase					DBCC CHECKIDENT( 'CourtCase', RESEED, 1 )
DELETE FROM CourtCaseOutcome			DBCC CHECKIDENT( 'CourtCaseOutcome', RESEED, 1 )
--DELETE FROM Defect
DELETE FROM DisabilityAssessment		DBCC CHECKIDENT( 'DisabilityAssessment', RESEED, 1)
DELETE FROM Disabilities				DBCC CHECKIDENT( 'Disabilities', RESEED, 1 )
DELETE FROM Diagnosis					DBCC CHECKIDENT( 'Diagnosis', RESEED, 1 )
DELETE FROM DocumentCatalog				DBCC CHECKIDENT( 'DocumentCatalog', RESEED, 1 )
DELETE FROM DocumentLink
DELETE FROM DomesticViolenceAssessment	DBCC CHECKIDENT( 'DomesticViolenceAssessment', RESEED, 1 )
DELETE FROM DVCrimes					DBCC CHECKIDENT( 'DVCrimes', RESEED, 1 )
DELETE FROM DynamicFormPaused			DBCC CHECKIDENT( 'DynamicFormPaused', RESEED, 1 )
DELETE FROM EducationSecondary		
DELETE FROM EducationAssessment			DBCC CHECKIDENT( 'EducationAssessment', RESEED, 1 )
DELETE FROM EducationHeadStart			--DBCC CHECKIDENT( 'EducationHeadStart', RESEED, 1 )	
DELETE FROM EducationSpecialNeeds		DBCC CHECKIDENT( 'EducationSpecialNeeds', RESEED, 1 )
DELETE FROM EducationSubjects			DBCC CHECKIDENT( 'EducationSubjects', RESEED, 1 )
DELETE FROM EmploymentAssessment		DBCC CHECKIDENT( 'EmploymentAssessment', RESEED, 1 )
DELETE FROM EmploymentAssessment_VA		--DBCC CHECKIDENT( 'EmploymentAssessment_VA', RESEED, 1 )
DELETE FROM EncounterActivity			DBCC CHECKIDENT( 'EncounterActivity', RESEED, 1 )
DELETE FROM Encounter					DBCC CHECKIDENT( 'Encounter', RESEED, 1 )
DELETE FROM EncounterEHR				DBCC CHECKIDENT( 'EncounterEHR', RESEED, 1 )
DELETE FROM Enrollment					DBCC CHECKIDENT( 'Enrollment', RESEED, 1 )
DELETE FROM EnrollmentAccount			DBCC CHECKIDENT( 'EnrollmentAccount', RESEED, 1 )
DELETE FROM EnrollmentCase				DBCC CHECKIDENT( 'EnrollmentCase', RESEED, 1 )
DELETE FROM EnrollmentEducation			DBCC CHECKIDENT( 'EnrollmentEducation', RESEED, 1 )
DELETE FROM EnrollmentParticipation
DELETE FROM EnrollmentPosted
DELETE FROM EnrollmentSchool			--DBCC CHECKIDENT( 'EnrollmentSchool', RESEED, 1 )
DELETE FROM EnrollmentWIA				DBCC CHECKIDENT( 'EnrollmentWIA', RESEED, 1 )
DELETE FROM EnrollmentHistory			DBCC CHECKIDENT( 'EnrollmentHistory', RESEED, 1)
DELETE FROM EnrollmentIndivdualPlan		--DBCC CHECKIDENT( 'EnrollmentIndivdualPlan', RESEED, 1 )
DELETE FROM EntityBasicClient

DELETE FROM RouteEntity WHERE EntityID NOT IN ( SELECT EntityID FROM osUsers )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProvider )
					   AND EntityID NOT IN ( SELECT EntityID FROM emEmployer )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProgFund )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityContact )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityPerson )

UPDATE Route
SET AssignedTo = NULL
WHERE AssignedTo NOT IN ( SELECT EntityID FROM osUsers )
					   AND AssignedTo NOT IN ( SELECT EntityID FROM cmProvider )
					   AND AssignedTo NOT IN ( SELECT EntityID FROM emEmployer )
					   AND AssignedTo NOT IN ( SELECT EntityID FROM cmProgFund )
					   AND AssignedTo NOT IN ( SELECT EntityID FROM EntityContact )
					   AND AssignedTo NOT IN ( SELECT EntityID FROM EntityPerson )


DELETE FROM Entity WHERE EntityID NOT IN ( SELECT EntityID FROM osUsers )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProvider )
					   AND EntityID NOT IN ( SELECT EntityID FROM emEmployer )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProgFund )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityContact )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityPerson )
DELETE FROM EmailAddress WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
DELETE FROM EntityList WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
DELETE FROM EntityTimeCode WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
DELETE FROM EntityChild WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
DELETE FROM EntityFlat WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
							OR ChildID NOT IN ( SELECT EntityID FROM Entity )							OR ChildID NOT IN ( SELECT EntityID FROM Entity )

DECLARE @LastID INT
SELECT @LastID = MAX(EntityID) FROM Entity
										DBCC CHECKIDENT( 'Entity', RESEED, @LastID)
SELECT @LastID = MAX(AddressID) FROM EmailAddress
										DBCC CHECKIDENT( 'EmailAddress', RESEED, @LastID)


DELETE FROM ForumPost WHERE EntityID NOT IN (SELECT EntityID FROM Entity)
DELETE FROM FamilyAlias					DBCC CHECKIDENT( 'FamilyAlias', RESEED, 1 )
DELETE FROM FileUpload					DBCC CHECKIDENT( 'FileUpload', RESEED, 1 )
DELETE FROM FinancialAssessment			DBCC CHECKIDENT( 'FinancialAssessment', RESEED, 1 )
DELETE FROM FinancialDeduction			DBCC CHECKIDENT( 'FinancialDeduction', RESEED, 1 )
DELETE FROM FinancialEvaluation			DBCC CHECKIDENT( 'FinancialEvaluation', RESEED, 1 )
DELETE FROM FinancialExpenseDetail		DBCC CHECKIDENT( 'FinancialExpenseDetail', RESEED, 1)
DELETE FROM FinancialExpense			DBCC CHECKIDENT( 'FinancialExpense', RESEED, 1 )
DELETE FROM FinancialIncome				DBCC CHECKIDENT( 'FinancialIncome', RESEED, 1 )
DELETE FROM FollowUp					DBCC CHECKIDENT( 'FollowUp', RESEED, 1 )
DELETE FROM FosterCareAssessment		DBCC CHECKIDENT( 'FosterCareAssessment', RESEED, 1 )
DELETE FROM GoalProgress				DBCC CHECKIDENT( 'GoalProgress', RESEED, 1 )
DELETE FROM HeadStartMedAssessment		DBCC CHECKIDENT( 'HeadStartMedAssessment', RESEED, 1 )
DELETE FROM HazMatAssessment			DBCC CHECKIDENT( 'HazMatAssessment', RESEED, 1)
DELETE FROM HazardousMaterial			DBCC CHECKIDENT( 'HazardousMaterial', RESEED, 1 )
DELETE FROM Hearing						DBCC CHECKIDENT( 'Hearing', RESEED, 1 )
DELETE FROM HearingCrime				DBCC CHECKIDENT( 'HearingCrime', RESEED, 1 )
DELETE FROM HIVAssessment				DBCC CHECKIDENT( 'HIVAssessment', RESEED, 1 )
DELETE FROM HmisDataAssessment			DBCC CHECKIDENT( 'HmisDataAssessment', RESEED, 1 )
DELETE FROM ImmunizationRecord			DBCC CHECKIDENT( 'ImmunizationRecord', RESEED, 1 )

DELETE FROM IncidentAssessmentType		
DELETE FROM IncidentAssessment			DBCC CHECKIDENT( 'IncidentAssessment', RESEED, 1 )
DELETE FROM IncidentAssessmentStaff
DELETE FROM IncidentParticipant
DELETE FROM Insurance					DBCC CHECKIDENT( 'Insurance', RESEED, 1 )
DELETE FROM InsuranceAssessment			DBCC CHECKIDENT( 'InsuranceAssessment', RESEED, 1 )
DELETE FROM LeaseAgreement				DBCC CHECKIDENT( 'LeaseAgreement', RESEED, 1 )
DELETE FROM LIHEAPAssessment			DBCC CHECKIDENT( 'LIHEAPAssessment', RESEED, 1 )
DELETE FROM LSPAssessment				DBCC CHECKIDENT( 'LSPAssessment', RESEED, 1 )
DELETE FROM MedicalAssessment			DBCC CHECKIDENT( 'MedicalAssessment', RESEED, 1 )
--DELETE FROM MedicationAssessment		DBCC CHECKIDENT( 'MedicationAssessment', RESEED, 1 )
--DELETE FROM Medication					DBCC CHECKIDENT( 'Medication', RESEED, 1 )
DELETE FROM MergeClient					DBCC CHECKIDENT( 'MergeClient', RESEED, 1 )
DELETE FROM Marriage 					DBCC CHECKIDENT( 'Marriage', RESEED, 1)
DELETE FROM MarriageSpouse				DBCC CHECKIDENT( 'MarriageSpouse', RESEED, 1)
DELETE FROM MilitaryServiceHistory		DBCC CHECKIDENT( 'MilitaryServiceHistory', RESEED, 1)
DELETE FROM MedicalAssessment_HealthDetails	--DBCC CHECKIDENT( 'MedicalAssessment_HealthDetails', RESEED, 1 )
--DELETE FROM MedicationLink				DBCC CHECKIDENT( 'MedicationLink', RESEED, 1 )
DELETE FROM NutritionPreference			DBCC CHECKIDENT( 'NutritionPreference', RESEED, 1)
DELETE FROM PrenatalCare				DBCC CHECKIDENT( 'PrenatalCare', RESEED, 1 )
DELETE FROM PregnancyAssessment			DBCC CHECKIDENT( 'PregnancyAssessment', RESEED, 1 )
DELETE FROM PrescriptClntRef			DBCC CHECKIDENT( 'PrescriptClntRef', RESEED, 1 )
DELETE FROM AssessmentPrescription		DBCC CHECKIDENT( 'AssessmentPrescription', RESEED, 1 )
DELETE FROM ProviderClientMeeting		DBCC CHECKIDENT( 'ProviderClientMeeting', RESEED, 1 )
DELETE FROM ProviderClientRelationship	DBCC CHECKIDENT( 'ProviderClientRelationship', RESEED, 1 )
DELETE FROM ProficientLanguage			
DELETE FROM QuarterlyWage				DBCC CHECKIDENT( 'QuarterlyWage', RESEED, 1 )
DELETE FROM RecentEntity				DBCC CHECKIDENT( 'RecentEntity', RESEED, 1 )
DELETE FROM Service						DBCC CHECKIDENT( 'Service', RESEED, 1 )
DELETE FROM ServiceActionPlan			DBCC CHECKIDENT( 'ServiceActionPlan', RESEED, 1 )
DELETE FROM ServiceAttendance			DBCC CHECKIDENT( 'ServiceAttendance', RESEED, 1 )
DELETE FROM ServiceCheckIn				DBCC CHECKIDENT( 'ServiceCheckIn', RESEED, 1 )
DELETE FROM ServiceCheckInPosted
DELETE FROM ServiceDirect				DBCC CHECKIDENT( 'ServiceDirect', RESEED, 1 )
DELETE FROM ServiceFamilyInfo
DELETE FROM ServiceIndirect				DBCC CHECKIDENT( 'ServiceIndirect', RESEED, 1 )
DELETE FROM ServiceInspection			DBCC CHECKIDENT( 'ServiceInspection', RESEED, 1 )
DELETE FROM ServiceParticipation		DBCC CHECKIDENT( 'ServiceParticipation', RESEED, 1 )
DELETE FROM ServiceReferral				DBCC CHECKIDENT( 'ServiceReferral', RESEED, 1 )
DELETE FROM ServiceReservation			DBCC CHECKIDENT( 'ServiceReservation', RESEED, 1 )
DELETE FROM ServiceWIA					DBCC CHECKIDENT( 'ServiceWIA', RESEED, 1 )
DELETE FROM StudentFood					DBCC CHECKIDENT( 'StudentFood', RESEED, 1 )
DELETE FROM TaskAttendance WHERE ParticipantID IN (SELECT ParticipantID FROM Participant WHERE EntityID NOT IN ( SELECT EntityID FROM Entity ))	DBCC CHECKIDENT( 'TaskAttendance', RESEED, 1 )
DELETE FROM TaskAlert WHERE ParticipantID IN (SELECT ParticipantID FROM Participant WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )) DBCC CHECKIDENT( 'TaskAlert', RESEED, 1 ) DBCC CHECKIDENT( 'TaskAlert', RESEED )

DELETE FROM dbo.ParticipantTaskHistory WHERE ParticipantID IN ( SELECT ParticipantID FROM Participant WHERE EntityID NOT IN (SELECT EntityID FROM Entity) )
DELETE FROM CUSTOM_Participant where participantid in (
	select participantid FROM Participant WHERE EntityID NOT IN (SELECT EntityID FROM Entity)
)
DELETE FROM Participant WHERE EntityID NOT IN (SELECT EntityID FROM Entity)
DELETE FROM Task WHERE ISNULL( TableName, '' ) <> 'Event' AND TaskID NOT IN (SELECT TaskID FROM Participant) DBCC CHECKIDENT( 'Task', RESEED, 1 ) DBCC CHECKIDENT( 'Task', RESEED )
DELETE FROM Task WHERE ForEntityID IN ( Select EntityID FROM Entity WHERE EntityID NOT IN ( SELECT EntityID FROM osUsers )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProvider )
					   AND EntityID NOT IN ( SELECT EntityID FROM emEmployer )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProgFund )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityContact )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityPerson ) )
DELETE FROM TimeEntry WHERE EntityID NOT IN ( SELECT EntityID FROM Entity )
DELETE FROM TimeEntry WHERE EntityID IN ( SelecT EntityID FROM Entity WHERE EntityID NOT IN ( SELECT EntityID FROM osUsers )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProvider )
					   AND EntityID NOT IN ( SELECT EntityID FROM emEmployer )
					   AND EntityID NOT IN ( SELECT EntityID FROM cmProgFund )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityContact )
					   AND EntityID NOT IN ( SELECT EntityID FROM EntityPerson ) )
DELETE FROM TimeGroup WHERE TimeGroupID NOT IN ( SELECT TimeGroupID FROM TimeEntry )
DELETE FROM Transportation				DBCC CHECKIDENT( 'Transportation', RESEED, 1 )
DELETE FROM VeteranAlias				
DELETE FROM VeteranAssessment			DBCC CHECKIDENT( 'VeteranAssessment', RESEED, 1 )
DELETE FROM VeteranAssessmentJournal	DBCC CHECKIDENT( 'VeteranAssessmentJournal', RESEED, 1 )
DELETE FROM VulnerabilityIndex			DBCC CHECKIDENT( 'VulnerabilityIndex', RESEED, 1)
DELETE FROM VulnerabilityHealthInsurance	DBCC CHECKIDENT( 'VulnerabilityHealthInsurance', RESEED, 1)
DELETE FROM VulnerabilityHousingBarriers	DBCC CHECKIDENT( 'VulnerabilityHousingBarriers', RESEED, 1)
DELETE FROM ApplicationVeteran			DBCC CHECKIDENT( 'ApplicationVeteran', RESEED, 1)
DELETE FROM VeteranDisability
DELETE FROM VeteranWorkHist				DBCC CHECKIDENT( 'VeteranWorkHist', RESEED, 1 )
DELETE FROM VulnerabilityMoneyType		DBCC CHECKIDENT( 'VulnerabilityMoneyType', RESEED, 1 )
DELETE FROM VulnerabilityWarsServedIn	DBCC CHECKIDENT( 'VulnerabilityWarsServedIn', RESEED, 1 )
DELETE FROM Visit						DBCC CHECKIDENT( 'Visit', RESEED, 1 )
DELETE FROM Wisconsin					DBCC CHECKIDENT( 'Wisconsin', RESEED, 1 )
DELETE FROM WaitingList					DBCC CHECKIDENT( 'WaitingList', RESEED, 1 )
DELETE FROM WaitingListHousing			DBCC CHECKIDENT( 'WaitingListHousing', RESEED, 1 )
DELETE FROM WorkflowInstance			DBCC CHECKIDENT( 'WorkflowInstance', RESEED, 1 )
DELETE FROM Wisconsin					DBCC CHECKIDENT( 'Wisconsin', RESEED, 1)
GO
IF( EXISTS( SELECT *
	FROM SysObjects O
	WHERE Name = 'CUSTOM_cmClient' ) )
	DELETE FROM CUSTOM_cmClient
GO
IF( EXISTS( SELECT *
	FROM SysObjects O
	WHERE Name = 'CUSTOM_Service' ) )
	DELETE FROM CUSTOM_Service
GO

ALTER TABLE Account CHECK CONSTRAINT ALL						ALTER TABLE Account ENABLE TRIGGER ALL
ALTER TABLE AccountAuthorization NOCHECK CONSTRAINT ALL			ALTER TABLE AccountAuthorization DISABLE TRIGGER ALL
ALTER TABLE AccountAuthorizationGoals NOCHECK CONSTRAINT ALL	ALTER TABLE AccountAuthorizationGoals DISABLE TRIGGER ALL
ALTER TABLE AccountBank CHECK CONSTRAINT ALL					ALTER TABLE AccountBank ENABLE TRIGGER ALL
ALTER TABLE AccountBill CHECK CONSTRAINT ALL					ALTER TABLE AccountBill ENABLE TRIGGER ALL
ALTER TABLE AccountBillAmount CHECK CONSTRAINT ALL				ALTER TABLE AccountBillAmount ENABLE TRIGGER ALL
ALTER TABLE AccountBillAmountHistory CHECK CONSTRAINT ALL		ALTER TABLE AccountBillAmountHistory ENABLE TRIGGER ALL
ALTER TABLE AccountBillHistory CHECK CONSTRAINT ALL				ALTER TABLE AccountBillHistory ENABLE TRIGGER ALL
ALTER TABLE AccountChild CHECK CONSTRAINT ALL					ALTER TABLE AccountChild ENABLE TRIGGER ALL
ALTER TABLE AccountInvoice CHECK CONSTRAINT ALL					ALTER TABLE AccountInvoice ENABLE TRIGGER ALL
ALTER TABLE AccountInvoiceItem CHECK CONSTRAINT ALL				ALTER TABLE AccountInvoiceItem ENABLE TRIGGER ALL
ALTER TABLE AccountRecurring CHECK CONSTRAINT ALL				ALTER TABLE AccountRecurring ENABLE TRIGGER ALL
ALTER TABLE AccountRecurringAmount CHECK CONSTRAINT ALL			ALTER TABLE AccountRecurringAmount ENABLE TRIGGER ALL
ALTER TABLE AccountRecurringBatch CHECK CONSTRAINT ALL			ALTER TABLE AccountRecurringBatch ENABLE TRIGGER ALL
ALTER TABLE AccountTransaction CHECK CONSTRAINT ALL				ALTER TABLE AccountTransaction ENABLE TRIGGER ALL
ALTER TABLE AccountTransactionBatch CHECK CONSTRAINT ALL		ALTER TABLE AccountTransactionBatch ENABLE TRIGGER ALL
ALTER TABLE AccountTransactionBill CHECK CONSTRAINT ALL			ALTER TABLE AccountTransactionBill ENABLE TRIGGER ALL
ALTER TABLE AccountVoucher CHECK CONSTRAINT ALL					ALTER TABLE AccountVoucher ENABLE TRIGGER ALL
ALTER TABLE AccountVoucherItem CHECK CONSTRAINT ALL				ALTER TABLE AccountVoucherItem ENABLE TRIGGER ALL
ALTER TABLE Application CHECK CONSTRAINT ALL					ALTER TABLE Application ENABLE TRIGGER ALL
ALTER TABLE ApplicationWIA CHECK CONSTRAINT ALL					ALTER TABLE ApplicationWIA ENABLE TRIGGER ALL
ALTER TABLE ApplicationVeteran CHECK CONSTRAINT ALL				ALTER TABLE ApplicationVeteran ENABLE TRIGGER ALL
ALTER TABLE Appeal CHECK CONSTRAINT ALL							ALTER TABLE Appeal ENABLE TRIGGER ALL
ALTER TABLE Assessment CHECK CONSTRAINT ALL						ALTER TABLE Assessment ENABLE TRIGGER ALL
ALTER TABLE AssessmentAddictionHealth CHECK CONSTRAINT ALL		ALTER TABLE AssessmentAddictionHealth ENABLE TRIGGER ALL
ALTER TABLE AssessmentEval CHECK CONSTRAINT ALL					ALTER TABLE AssessmentEval ENABLE TRIGGER ALL
ALTER TABLE AssessmentWorkHist CHECK CONSTRAINT ALL				ALTER TABLE AssessmentWorkHist ENABLE TRIGGER ALL
ALTER TABLE AssessSelfMatrix CHECK CONSTRAINT ALL				ALTER TABLE AssessSelfMatrix ENABLE TRIGGER ALL
ALTER TABLE AssetAssessment CHECK CONSTRAINT ALL				ALTER TABLE AssetAssessment ENABLE TRIGGER ALL
ALTER TABLE AssetsSavingsAccount CHECK CONSTRAINT ALL			ALTER TABLE AssetsSavingsAccount ENABLE TRIGGER ALL
ALTER TABLE BarList CHECK CONSTRAINT ALL						ALTER TABLE BarList ENABLE TRIGGER ALL
ALTER TABLE BarListReason CHECK CONSTRAINT ALL					ALTER TABLE BarListReason ENABLE TRIGGER ALL
ALTER TABLE BatchTransaction CHECK CONSTRAINT ALL				ALTER TABLE BatchTransaction ENABLE TRIGGER ALL
ALTER TABLE Call CHECK CONSTRAINT ALL							ALTER TABLE Call ENABLE TRIGGER ALL
ALTER TABLE CallReason CHECK CONSTRAINT ALL						ALTER TABLE CallReason ENABLE TRIGGER ALL
ALTER TABLE ChronicHomeless CHECK CONSTRAINT ALL				ALTER TABLE ChronicHomeless ENABLE TRIGGER ALL
ALTER TABLE ClientFiles CHECK CONSTRAINT ALL					ALTER TABLE ClientFiles ENABLE TRIGGER ALL
ALTER TABLE ClientIdentifier CHECK CONSTRAINT ALL				ALTER TABLE ClientIdentifier ENABLE TRIGGER ALL
ALTER TABLE ClientPhone CHECK CONSTRAINT ALL					ALTER TABLE ClientPhone ENABLE TRIGGER ALL
ALTER TABLE ClientRace CHECK CONSTRAINT ALL						ALTER TABLE ClientRace ENABLE TRIGGER ALL
ALTER TABLE ClientScreening CHECK CONSTRAINT ALL				ALTER TABLE ClientScreening ENABLE TRIGGER ALL
ALTER TABLE ClientSignature CHECK CONSTRAINT ALL				ALTER TABLE ClientSignature ENABLE TRIGGER ALL
ALTER TABLE cmAddictionHealth CHECK CONSTRAINT ALL				ALTER TABLE cmAddictionHealth ENABLE TRIGGER ALL
ALTER TABLE cmAddress CHECK CONSTRAINT ALL						ALTER TABLE cmAddress ENABLE TRIGGER ALL
ALTER TABLE cmAlias CHECK CONSTRAINT ALL						ALTER TABLE cmAlias ENABLE TRIGGER ALL
ALTER TABLE cmCaseAssign CHECK CONSTRAINT ALL					ALTER TABLE cmCaseAssign ENABLE TRIGGER ALL
ALTER TABLE cmClient CHECK CONSTRAINT ALL						ALTER TABLE cmClient ENABLE TRIGGER ALL
ALTER TABLE cmClient_Address CHECK CONSTRAINT ALL				ALTER TABLE cmClient_Address ENABLE TRIGGER ALL

ALTER TABLE cmClntEval CHECK CONSTRAINT ALL						ALTER TABLE cmClntEval ENABLE TRIGGER ALL
ALTER TABLE cmDocumentCheckList CHECK CONSTRAINT ALL			ALTER TABLE cmDocumentCheckList ENABLE TRIGGER ALL
ALTER TABLE cmFamilyAccFile CHECK CONSTRAINT ALL				ALTER TABLE cmFamilyAccFile ENABLE TRIGGER ALL
ALTER TABLE cmFamilyMemFile CHECK CONSTRAINT ALL				ALTER TABLE cmFamilyMemFile ENABLE TRIGGER ALL
ALTER TABLE cmFinancialAssess CHECK CONSTRAINT ALL				ALTER TABLE cmFinancialAssess ENABLE TRIGGER ALL
ALTER TABLE cmGoals CHECK CONSTRAINT ALL						ALTER TABLE cmGoals ENABLE TRIGGER ALL
ALTER TABLE cmInterOther CHECK CONSTRAINT ALL					ALTER TABLE cmInterOther ENABLE TRIGGER ALL
ALTER TABLE cmInfoRelease CHECK CONSTRAINT ALL					ALTER TABLE cmInfoRelease ENABLE TRIGGER ALL
ALTER TABLE cmWorkHistoryHeadStart CHECK CONSTRAINT ALL			ALTER TABLE cmWorkHistoryHeadStart ENABLE TRIGGER ALL
ALTER TABLE cmWorkHistHSHistory CHECK CONSTRAINT ALL			ALTER TABLE cmWorkHistHSHistory ENABLE TRIGGER ALL
ALTER TABLE cmTestRslts CHECK CONSTRAINT ALL					ALTER TABLE cmTestRslts ENABLE TRIGGER ALL
ALTER TABLE cmWorkHist CHECK CONSTRAINT ALL						ALTER TABLE cmWorkHist ENABLE TRIGGER ALL
ALTER TABLE cmWorkHistHistory CHECK CONSTRAINT ALL				ALTER TABLE cmWorkHistHistory ENABLE TRIGGER ALL
ALTER TABLE WorkHistoryBenefits CHECK CONSTRAINT ALL			ALTER TABLE WorkHistoryBenefits ENABLE TRIGGER ALL
ALTER TABLE Legal CHECK CONSTRAINT ALL							ALTER TABLE Legal ENABLE TRIGGER ALL
ALTER TABLE Spirituality CHECK CONSTRAINT ALL					ALTER TABLE Spirituality ENABLE TRIGGER ALL
ALTER TABLE Transportation CHECK CONSTRAINT ALL					ALTER TABLE Transportation ENABLE TRIGGER ALL
ALTER TABLE CourtCase CHECK CONSTRAINT ALL						ALTER TABLE CourtCase ENABLE TRIGGER ALL
ALTER TABLE CourtCaseOutcome CHECK CONSTRAINT ALL				ALTER TABLE CourtCaseOutcome ENABLE TRIGGER ALL
--ALTER TABLE Defect CHECK CONSTRAINT ALL							ALTER TABLE Defect ENABLE TRIGGER ALL
ALTER TABLE DietaryAssessment CHECK CONSTRAINT ALL				ALTER TABLE DietaryAssessment ENABLE TRIGGER ALL
ALTER TABLE DietaryTypes CHECK CONSTRAINT ALL					ALTER TABLE DietaryTypes ENABLE TRIGGER ALL
ALTER TABLE Disabilities CHECK CONSTRAINT ALL					ALTER TABLE Disabilities ENABLE TRIGGER ALL
ALTER TABLE Diagnosis CHECK CONSTRAINT ALL						ALTER TABLE Diagnosis ENABLE TRIGGER ALL
ALTER TABLE DocumentCatalog CHECK CONSTRAINT ALL				ALTER TABLE DocumentCatalog ENABLE TRIGGER ALL
ALTER TABLE DocumentLink CHECK CONSTRAINT ALL					ALTER TABLE DocumentLink ENABLE TRIGGER ALL
ALTER TABLE DomesticViolenceAssessment CHECK CONSTRAINT ALL		ALTER TABLE DomesticViolenceAssessment ENABLE TRIGGER ALL
ALTER TABLE DVCrimes CHECK CONSTRAINT ALL						ALTER TABLE DVCrimes ENABLE TRIGGER ALL
ALTER TABLE DynamicFormPaused CHECK CONSTRAINT ALL				ALTER TABLE DynamicFormPaused ENABLE TRIGGER ALL
ALTER TABLE EducationAssessment CHECK CONSTRAINT ALL			ALTER TABLE EducationAssessment ENABLE TRIGGER ALL
ALTER TABLE EducationSpecialNeeds CHECK CONSTRAINT ALL			ALTER TABLE EducationSpecialNeeds ENABLE TRIGGER ALL
ALTER TABLE EducationSubjects CHECK CONSTRAINT ALL				ALTER TABLE EducationSubjects ENABLE TRIGGER ALL
ALTER TABLE EducationHeadStart CHECK CONSTRAINT ALL				ALTER TABLE EducationHeadStart ENABLE TRIGGER ALL
ALTER TABLE EmploymentAssessment CHECK CONSTRAINT ALL			ALTER TABLE EmploymentAssessment ENABLE TRIGGER ALL
ALTER TABLE EmploymentAssessment_VA CHECK CONSTRAINT ALL		ALTER TABLE EmploymentAssessment_VA ENABLE TRIGGER ALL
ALTER TABLE EncounterActivity CHECK CONSTRAINT ALL				ALTER TABLE EncounterActivity ENABLE TRIGGER ALL
ALTER TABLE Encounter CHECK CONSTRAINT ALL						ALTER TABLE Encounter ENABLE TRIGGER ALL
ALTER TABLE EncounterEHR CHECK CONSTRAINT ALL					ALTER TABLE EncounterEHR ENABLE TRIGGER ALL
ALTER TABLE Enrollment CHECK CONSTRAINT ALL						ALTER TABLE Enrollment ENABLE TRIGGER ALL
ALTER TABLE EnrollmentCase CHECK CONSTRAINT ALL					ALTER TABLE EnrollmentCase ENABLE TRIGGER ALL
ALTER TABLE EnrollmentAccount CHECK CONSTRAINT ALL				ALTER TABLE EnrollmentAccount ENABLE TRIGGER ALL
ALTER TABLE EnrollmentEducation CHECK CONSTRAINT ALL			ALTER TABLE EnrollmentEducation ENABLE TRIGGER ALL
ALTER TABLE EnrollmentParticipation CHECK CONSTRAINT ALL		ALTER TABLE EnrollmentParticipation ENABLE TRIGGER ALL
ALTER TABLE EnrollmentPosted CHECK CONSTRAINT ALL				ALTER TABLE EnrollmentPosted ENABLE TRIGGER ALL
ALTER TABLE EnrollmentSchool CHECK CONSTRAINT ALL				ALTER TABLE EnrollmentSchool ENABLE TRIGGER ALL
ALTER TABLE EnrollmentWIA CHECK CONSTRAINT ALL					ALTER TABLE EnrollmentWIA ENABLE TRIGGER ALL
ALTER TABLE EnrollmentIndivdualPlan CHECK CONSTRAINT ALL		ALTER TABLE EnrollmentIndivdualPlan ENABLE TRIGGER ALL
ALTER TABLE EnrollmentHistory CHECK CONSTRAINT ALL				ALTER TABLE EnrollmentHistory ENABLE TRIGGER ALL
ALTER TABLE EntityBasicClient CHECK CONSTRAINT ALL				ALTER TABLE EntityBasicClient ENABLE TRIGGER ALL
ALTER TABLE EntityChild CHECK CONSTRAINT ALL					ALTER TABLE EntityChild ENABLE TRIGGER ALL
ALTER TABLE EntityFlat CHECK CONSTRAINT ALL						ALTER TABLE EntityFlat ENABLE TRIGGER ALL
ALTER TABLE EntityList CHECK CONSTRAINT ALL						ALTER TABLE EntityList ENABLE TRIGGER ALL
ALTER TABLE EntityTimeCode CHECK CONSTRAINT	ALL					ALTER TABLE EntityTimeCode ENABLE TRIGGER ALL
ALTER TABLE FamilyAlias CHECK CONSTRAINT ALL					ALTER TABLE FamilyAlias ENABLE TRIGGER ALL
ALTER TABLE FileUpload CHECK CONSTRAINT ALL						ALTER TABLE FileUpload ENABLE TRIGGER ALL
ALTER TABLE FinancialAssessment CHECK CONSTRAINT ALL			ALTER TABLE FinancialAssessment ENABLE TRIGGER ALL
ALTER TABLE FinancialDeduction CHECK CONSTRAINT ALL				ALTER TABLE FinancialDeduction ENABLE TRIGGER ALL
ALTER TABLE FinancialEvaluation CHECK CONSTRAINT ALL			ALTER TABLE FinancialEvaluation ENABLE TRIGGER ALL
ALTER TABLE FinancialExpenseDetail CHECK CONSTRAINT ALL			ALTER TABLE FinancialExpenseDetail ENABLE TRIGGER ALL
ALTER TABLE FinancialExpense CHECK CONSTRAINT ALL				ALTER TABLE FinancialExpense ENABLE TRIGGER ALL
ALTER TABLE FinancialIncome CHECK CONSTRAINT ALL				ALTER TABLE FinancialIncome ENABLE TRIGGER ALL
ALTER TABLE FollowUp CHECK CONSTRAINT ALL						ALTER TABLE FollowUp ENABLE TRIGGER ALL
ALTER TABLE FosterCareAssessment CHECK CONSTRAINT ALL			ALTER TABLE FosterCareAssessment ENABLE TRIGGER ALL
ALTER TABLE GoalProgress CHECK CONSTRAINT ALL					ALTER TABLE GoalProgress ENABLE TRIGGER ALL
ALTER TABLE HeadStartMedAssessment CHECK CONSTRAINT ALL			ALTER TABLE HeadStartMedAssessment ENABLE TRIGGER ALL
ALTER TABLE HazMatAssessment CHECK CONSTRAINT ALL				ALTER TABLE HazMatAssessment ENABLE TRIGGER ALL
ALTER TABLE HazardousMaterial CHECK CONSTRAINT ALL				ALTER TABLE HazardousMaterial ENABLE TRIGGER ALL
ALTER TABLE Hearing CHECK CONSTRAINT ALL						ALTER TABLE Hearing ENABLE TRIGGER ALL
ALTER TABLE HearingCrime CHECK CONSTRAINT ALL					ALTER TABLE HearingCrime ENABLE TRIGGER ALL
ALTER TABLE HIVAssessment CHECK CONSTRAINT ALL					ALTER TABLE HIVAssessment ENABLE TRIGGER ALL
ALTER TABLE HmisDataAssessment CHECK CONSTRAINT ALL				ALTER TABLE HmisDataAssessment ENABLE TRIGGER ALL
ALTER TABLE ImmunizationRecord CHECK CONSTRAINT ALL				ALTER TABLE ImmunizationRecord ENABLE TRIGGER ALL

ALTER TABLE IncidentAssessment CHECK CONSTRAINT ALL				ALTER TABLE IncidentAssessment ENABLE TRIGGER ALL
ALTER TABLE IncidentAssessmentType CHECK CONSTRAINT ALL			ALTER TABLE IncidentAssessmentType ENABLE TRIGGER ALL
ALTER TABLE Insurance CHECK CONSTRAINT ALL						ALTER TABLE Insurance ENABLE TRIGGER ALL
ALTER TABLE InsuranceAssessment CHECK CONSTRAINT ALL			ALTER TABLE InsuranceAssessment ENABLE TRIGGER ALL
ALTER TABLE LeaseAgreement CHECK CONSTRAINT ALL					ALTER TABLE LeaseAgreement ENABLE TRIGGER ALL
ALTER TABLE LetterEntity CHECK CONSTRAINT ALL					ALTER TABLE LetterEntity ENABLE TRIGGER ALL
ALTER TABLE LIHEAPAssessment CHECK CONSTRAINT ALL				ALTER TABLE LIHEAPAssessment ENABLE TRIGGER ALL
ALTER TABLE MedicalAssessment CHECK CONSTRAINT ALL				ALTER TABLE MedicalAssessment ENABLE TRIGGER ALL
ALTER TABLE MilitaryServiceHistory CHECK CONSTRAINT ALL			ALTER TABLE MilitaryServiceHistory ENABLE TRIGGER ALL
ALTER TABLE MedicalAssessment_HealthDetails CHECK CONSTRAINT ALL	ALTER TABLE MedicalAssessment_HealthDetails ENABLE TRIGGER ALL
--ALTER TABLE MedicationLink CHECK CONSTRAINT ALL					ALTER TABLE MedicationLink ENABLE TRIGGER ALL
--ALTER TABLE MedicationAssessment CHECK CONSTRAINT ALL			ALTER TABLE MedicationAssessment ENABLE TRIGGER ALL
--ALTER TABLE Medication CHECK CONSTRAINT ALL						ALTER TABLE Medication ENABLE TRIGGER ALL
ALTER TABLE NutritionPreference CHECK CONSTRAINT ALL			ALTER TABLE NutritionPreference ENABLE TRIGGER ALL
ALTER TABLE PrenatalCare CHECK CONSTRAINT ALL					ALTER TABLE PrenatalCare ENABLE TRIGGER ALL
ALTER TABLE PrescriptClntRef CHECK CONSTRAINT ALL				ALTER TABLE PrescriptClntRef ENABLE TRIGGER ALL
ALTER TABLE PregnancyAssessment CHECK CONSTRAINT ALL			ALTER TABLE PregnancyAssessment ENABLE TRIGGER ALL
ALTER TABLE AssessmentPrescription CHECK CONSTRAINT ALL			ALTER TABLE AssessmentPrescription ENABLE TRIGGER ALL
ALTER TABLE ProviderClientMeeting CHECK CONSTRAINT ALL			ALTER TABLE ProviderClientMeeting ENABLE TRIGGER ALL
ALTER TABLE ProviderClientRelationship CHECK CONSTRAINT ALL		ALTER TABLE ProviderClientRelationship ENABLE TRIGGER ALL
ALTER TABLE ProficientLanguage CHECK CONSTRAINT ALL				ALTER TABLE ProficientLanguage ENABLE TRIGGER ALL
ALTER TABLE QuarterlyWage CHECK CONSTRAINT ALL					ALTER TABLE QuarterlyWage ENABLE TRIGGER ALL
ALTER TABLE RecentEntity CHECK CONSTRAINT ALL					ALTER TABLE RecentEntity ENABLE TRIGGER ALL

ALTER TABLE Service CHECK CONSTRAINT ALL						ALTER TABLE Service ENABLE TRIGGER ALL
ALTER TABLE ServiceActionPlan CHECK CONSTRAINT ALL				ALTER TABLE ServiceActionPlan ENABLE TRIGGER ALL
ALTER TABLE ServiceAttendance CHECK CONSTRAINT ALL				ALTER TABLE ServiceAttendance ENABLE TRIGGER ALL
ALTER TABLE ServiceCheckIn CHECK CONSTRAINT ALL					ALTER TABLE ServiceCheckIn ENABLE TRIGGER ALL
ALTER TABLE ServiceCheckInPosted CHECK CONSTRAINT ALL			ALTER TABLE ServiceCheckInPosted ENABLE TRIGGER ALL
ALTER TABLE ServiceDirect CHECK CONSTRAINT ALL					ALTER TABLE ServiceDirect ENABLE TRIGGER ALL
ALTER TABLE ServiceFamilyInfo CHECK CONSTRAINT ALL				ALTER TABLE ServiceFamilyInfo ENABLE TRIGGER ALL
ALTER TABLE ServiceIndirect CHECK CONSTRAINT ALL				ALTER TABLE ServiceIndirect ENABLE TRIGGER ALL
ALTER TABLE ServiceInspection CHECK CONSTRAINT ALL				ALTER TABLE ServiceInspection ENABLE TRIGGER ALL
ALTER TABLE ServiceParticipation CHECK CONSTRAINT ALL			ALTER TABLE ServiceParticipation ENABLE TRIGGER ALL
ALTER TABLE ServiceReferral CHECK CONSTRAINT ALL				ALTER TABLE ServiceReferral ENABLE TRIGGER ALL
ALTER TABLE ServiceReservation CHECK CONSTRAINT ALL				ALTER TABLE ServiceReservation ENABLE TRIGGER ALL
ALTER TABLE ServiceWIA CHECK CONSTRAINT ALL						ALTER TABLE ServiceWIA ENABLE TRIGGER ALL
ALTER TABLE StudentFood CHECK CONSTRAINT ALL					ALTER TABLE StudentFood ENABLE TRIGGER ALL
ALTER TABLE TimeEntry CHECK CONSTRAINT ALL						ALTER TABLE TimeEntry ENABLE TRIGGER ALL
ALTER TABLE VeteranAssessment CHECK CONSTRAINT ALL				ALTER TABLE VeteranAssessment ENABLE TRIGGER ALL
ALTER TABLE VeteranAssessmentJournal CHECK CONSTRAINT ALL		ALTER TABLE VeteranAssessmentJournal ENABLE TRIGGER ALL
ALTER TABLE VulnerabilityIndex CHECK CONSTRAINT ALL				ALTER TABLE VulnerabilityIndex ENABLE TRIGGER ALL
ALTER TABLE VulnerabilityHealthInsurance CHECK CONSTRAINT ALL	ALTER TABLE VulnerabilityHealthInsurance ENABLE TRIGGER ALL
ALTER TABLE Visit CHECK CONSTRAINT ALL							ALTER TABLE Visit ENABLE TRIGGER ALL
ALTER TABLE VulnerabilityMoneyType CHECK CONSTRAINT ALL			ALTER TABLE VulnerabilityMoneyType ENABLE TRIGGER ALL
ALTER TABLE VulnerabilityHousingBarriers CHECK CONSTRAINT ALL	ALTER TABLE VulnerabilityHousingBarriers ENABLE TRIGGER ALL
ALTER TABLE VulnerabilityWarsServedIn CHECK CONSTRAINT ALL		ALTER TABLE VulnerabilityWarsServedIn ENABLE TRIGGER ALL
ALTER TABLE WaitingList CHECK CONSTRAINT ALL					ALTER TABLE WaitingList ENABLE TRIGGER ALL
ALTER TABLE WaitingListHousing CHECK CONSTRAINT ALL				ALTER TABLE WaitingListHousing ENABLE TRIGGER ALL
ALTER TABLE WorkflowInstance CHECK CONSTRAINT ALL				ALTER TABLE WorkflowInstance ENABLE TRIGGER ALL
ALTER TABLE Wisconsin CHECK CONSTRAINT ALL						ALTER TABLE Wisconsin ENABLE TRIGGER ALL




IF( NOT EXISTS( SELECT *
	FROM cmClient
	WHERE ClientID = 0 ) )
   BEGIN
	ALTER TABLE cmClient DISABLE TRIGGER ALL
	SET IDENTITY_INSERT cmClient ON 
	INSERT INTO cmClient( ClientID, [Name], LastName, FirstName, RestrictIntake, RestrictOrg, OrgID, CreatedBy, CreatedDate, UpdatedBy, UpdatedDate, ActiveStatus )
	VALUES( 0, 'No Client', 'Client', 'No', 1, 'U', 'DSI', 'DSI', '1/1/2005', 'DSI', '1/1/2005', 'A' )
	SET IDENTITY_INSERT cmClient OFF
	ALTER TABLE cmClient ENABLE TRIGGER ALL
   END

UPDATE osNextKey
SET KeyValue = 1
WHERE TableName IN ('cmAddictionHealth', 'cmAddress', 'cmAlias', 'cmCaseAssign', 'cmClient', 'cmClntEval', 'cmFamilyAccFile',
	'cmFamilyMemFile', 'cmFinancialAssess', 'cmGoals', 'cmInfoRelease', 'cmInterOther', 'cmNotification', 'cmTestRslts',
	'cmWorkHist', 'FileUpload')

--DECLARE @Training VARCHAR(50) = , 
--		@Production VARCHAR(50) = 
--		
--UPDATE DefectUsers
--SET DUID = @Production + '-' + UserID,
--CustomerID = @Production
--FROM DefectUsers
--WHERE CustomerID = @Training
--AND @Production + '-' + UserID NOT IN ( SELECT DUID FROM DefectUsers )



/*
//Production only
UPDATE osUsers
SET ToolAccess = ToolAccess & 1577322056
WHERE UserID <> 'DSI'
   OR DomainID > 0;
   */


	
